[tool.poetry]
name = "repl_python3_Leaderboards"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
gevent = "^21.1.2"
discord = "^1.7.3"
requests = "^2.25.1"
steamleaderboards = "^0.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
